### ISSUE TITLE
unable to add "typeselect" to lightbox

### ISSUE THREAD

**Issue by shayzalman** [DHTMLX/angular2-gantt-demo#5]
I have tried to follow a few forum posts telling to add this config params:
gantt.config.lightbox.sections = [
  { name: "description", height: 38, map_to: "text", type: "textarea", focus: true },
  { name: "type", type: "typeselect", map_to: "type" },
  { name: "time", height: 72, type: "duration", map_to: "auto" }
];

gantt.config.lightbox.project_sections = [
  { name: "title", height: 20, map_to: "text", type: "textarea", focus: true },
  { name: "type", type: "typeselect", map_to: "type" },
  { name: "details", height: 70, map_to: "details", type: "textarea" },
  { name: "time", height: 72, type: "time", map_to: "auto" }
];

gantt.config.lightbox.milestone_sections = [
  { name: "title", height: 20, map_to: "text", type: "textarea", focus: true },
  { name: "type", type: "typeselect", map_to: "type" },
  { name: "details", height: 70, map_to: "details", type: "textarea" },
  { name: "time", height: 72, type: "time", map_to: "auto" }
];

It seems to work fine here:
https://docs.dhtmlx.com/gantt/snippet/d4f83aa7

but in my component I don't see the type select, no matter what I do.

**Comment by AlexKlimenkov** [comment]
Hi,
"typeselect" is not included in the Standard version of the gantt (the one which is published here) - https://docs.dhtmlx.com/gantt/desktop__task_types.html
You'll need a Professional edition to use it, i.e. either Commercial, Enterprise or Evaluation versions
http://docs.dhtmlx.com/gantt/snippet/90cc796f
