### ISSUE TITLE
Chart not showing UP.

### ISSUE THREAD

**Issue by 3agessolutions** [DHTMLX/angular2-gantt-demo#6]
Gantt chart is showing only if called in starting component in application. It is not showing if chart added in component loaded via router.

**Comment by AlexKlimenkov** [comment]
Hi,
can you please make some minimal demo, so we could reproduce the issue?

**Comment by AlexKlimenkov** [comment]
If there are no js errors in browser console, then the issue can have something to do with relative sizes of gantt element

As a quick check you can try setting some fixed height value for #gantt_here element https://github.com/DHTMLX/angular2-gantt-demo/blob/master/src/app/components/gantt.component.ts#L22
e.g.
`template: "<div #gantt_here style='width: 100%; height: 600px;'></div>",`
If it fixes the problem, that would mean :host size is not set properly.

Closing the issue due inactivity, feel free to open if you have new info
